Repository ssafy-vue/kr.vuejs.org, pull requests merged in 2022-11, with the labels that each got.

#2 Hexo depoloy 과정에서 CNAME이 초기화되는 문제 수정
  _config.yml
  package.json
  yarn.lock
Labels: Ops

#4 vue router 문서 링크 업데이트
  src/v2/guide/routing.md
  themes/vue/layout/partials/ecosystem_dropdown.ejs
Labels: 문서

#40 스타일 가이드 - Prop 이름 규칙 지정(casing)
  src/v2/style-guide/index.md
Labels: 스타일가이드

#42 스타일가이드 맞춤법 수정
  src/v2/style-guide/index.md
Labels: 스타일가이드

#43 스타일 가이드 - 속성 값에 따옴표
  src/v2/style-guide/index.md
Labels: 스타일가이드

#46 스타일 가이드 - v-if와 v-for를 동시에 사용하지 마세요 - 자세한 설명, 컴포넌트 파일
  src/v2/style-guide/index.md
Labels: 스타일가이드

#47 스타일 가이드 - 싱글 파일 컴포넌트 이름 규칙 지정
  src/v2/style-guide/index.md
Labels: 스타일가이드

#49 스타일 가이드 #17
  src/v2/style-guide/index.md
Labels: 스타일가이드

#48 스타일 가이드 - 축약형 디렉티브 #38
  src/v2/style-guide/index.md
Labels: 스타일가이드

#50 스타일 가이드 - 템플릿, JS/JSX에서의 컴포넌트 이름 규칙 지정(casing)
  src/v2/style-guide/index.md
Labels: 스타일가이드

#53 스타일 가이드 - 전체 이름 컴포넌트 이름 #32
  src/v2/style-guide/index.md
Labels: 스타일가이드

#54 Typescript -NPM #16
  src/v2/guide/typescript.md
Labels: 가이드

#56 스타일 가이드 - 컴포넌트 스타일 스코프
  src/v2/style-guide/index.md
Labels: 스타일가이드

#55 Unit Testing
  src/v2/guide/testing.md
Labels: 가이드

#59 스타일 가이드 - 컴포넌트 스타일 스코프 - 자세한 설명 #21
  src/v2/style-guide/index.md
Labels: 스타일가이드

#60 스타일 가이드 - 베이스 컴포넌트 이름 #25 - (draft 상태로 처리)
  src/v2/style-guide/index.md
Labels: 스타일가이드
